In [ ]:
import numpy as np


# this is the diff B.W python list and **np**

In [ ]:
#list
python_list = [1,2,3,4,5]


[1, 2, 3, 4, 5]

NumPy array --> np.array([1,2,3,4,5])

In [ ]:
numpy_array = np.array([1,2,3,4,5])
numpy_array

array([1, 2, 3, 4, 5])

In [ ]:
print("python list:",python_list)
print("NumPy:", numpy_array)


print("type of python list: ", python_list)
print("type of numpy array: ", numpy_array)

print("python list (req loop to add): ",[ i + 10 for i in python_list])
print("NumPy array ADD--->(vectorized): ", numpy_array + 10 )

python list: [1, 2, 3, 4, 5]
NumPy: [1 2 3 4 5]
type of python list:  [1, 2, 3, 4, 5]
type of numpy array:  [1 2 3 4 5]
python list (req loop to add):  [11, 12, 13, 14, 15]
NumPy array ADD--->(vectorized):  [11 12 13 14 15]


# **Methods of creating NumPy array!!**

In [ ]:
#Method-1: (creating like python list!!)
arr1 = np.array([1,2,3,4,5,6,7])
print(arr1)

#method-2 : (similar to python range) using np.arange!!
arr2 = np.arange(0,10,2) # start , stop , step
print(arr2)

#method-3 : using np.linspace() - evenly spaced numbers
arr3 = np.linspace(0, 1, 5) # start, stop , number of elements
print("using linspace: ", arr3)

#method-4 : creating arrays of zeros
zeros = np.zeros(5)
print("Zeros: ", zeros)

#methods-5: Creating arrays of ones!!
ones = np.ones(5)
print("array of ones: ",ones)

#method-6: Creating array with a specific value!!
full = np.full(6 , 7)   #---> (no of item, item )
print("array of ", full)


#method-7 : Creating Identity Martrix
Identity = np.eye(5)
print("Identity: \n", Identity)

#method-8 : Random arrays
random_arr = np.random.rand(3) #---> Uniform distribution [0,1]
print("random(uniform): ",random_arr)

#method-9 : Randint!!
random_int = np.random.randint(1,14,size = 5) #--> [Low , High , size=?]
print("randint: ",random_int)



[1 2 3 4 5 6 7]
[0 2 4 6 8]
using linspace:  [0.   0.25 0.5  0.75 1.  ]
Zeros:  [0. 0. 0. 0. 0.]
array of ones:  [1. 1. 1. 1. 1.]
array of  [7 7 7 7 7 7]
Identity: 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
random(uniform):  [0.54717764 0.45102224 0.89239271]
randint:  [13 10  3 12  6]


# **NumPy Data Type(dtype)**

**Type inference and common types**

In [ ]:
arr_int = np.array([1,2,3])
arr_float = np.array([1.0,2.0,3.0,4.0,5.0])
arr_mix = np.array([1,2,3.5,4,2,5])


print(f"int type: {arr_int.dtype}")
print(f"float type: {arr_float.dtype}")
print(f"mix type: {arr_mix.dtype}")

#specifying types
arr_1 = np.array([1,2,3], dtype= np.float64)
arr_2 = arr_int.astype(np.float32)

print(f"arr_1 type: {arr_1.dtype}")
print(f"arr_2 type: {arr_2.dtype}")



int type: int64
float type: float64
mix type: float64
arr_1 type: float64
arr_2 type: float32


# **Multi-Dimensional Array:**

In [ ]:
#1D array = [1,2,3,4,5]

#2D array(matrix)
matrix_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix_2d)
print(f"shape: {matrix_2d.shape}")  #row,colums
print(f"dimension: {matrix_2d.ndim}")
print(f"size(no of elements): {matrix_2d.size}")
print(f"type: {matrix_2d.dtype}")

#3D array
matrix_3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(matrix_3d)
print(f"shape: {matrix_3d.shape}")  #row,colums
print(f"dimension: {matrix_3d.ndim}")
print(f"size(no of elements): {matrix_3d.size}")
print(f"type: {matrix_3d.dtype}")

#matrix_0 : creating matrix of zeros
zeros = np.zeros((4,3))   #row,colums
print("Zeros: \n", zeros)

#matrix_1: Creating matrix of ones!!
ones = np.ones((3,4,3))   #row,colums
print("matrix of ones: \n",ones)



[[1 2 3]
 [4 5 6]
 [7 8 9]]
shape: (3, 3)
dimension: 2
size(no of elements): 9
type: int64
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
shape: (2, 2, 2)
dimension: 3
size(no of elements): 8
type: int64
Zeros: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
matrix of ones: 
 [[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


# **Array Attributes!!**

In [ ]:
arr = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],
                [[9,10,11,12],[13,14,15,16],[17,18,19,20]],
                [[17,18,19,20],[21,22,23,24],[1,2,3,4]]])

print("array: \n",arr)
print("shape: ",arr.shape)
print("dimension: ",arr.ndim)
print("type: ",arr.dtype)
print(f"size: {arr.size} elements")
print(f"itemsize: {arr.itemsize} bytes")
print(f"nbytes: {arr.nbytes} bytes")
print(f"T (transpose): \n{arr.T}")
print(f"shape of arr.T: {arr.T.shape} ")
print(f"dimension of arr.T: {arr.T.ndim} ")


array: 
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[ 9 10 11 12]
  [13 14 15 16]
  [17 18 19 20]]

 [[17 18 19 20]
  [21 22 23 24]
  [ 1  2  3  4]]]
shape:  (3, 3, 4)
dimension:  3
type:  int64
size: 36 elements
itemsize: 8 bytes
nbytes: 288 bytes
T (transpose): 
[[[ 1  9 17]
  [ 5 13 21]
  [ 9 17  1]]

 [[ 2 10 18]
  [ 6 14 22]
  [10 18  2]]

 [[ 3 11 19]
  [ 7 15 23]
  [11 19  3]]

 [[ 4 12 20]
  [ 8 16 24]
  [12 20  4]]]
shape of arr.T: (4, 3, 3) 
dimension of arr.T: 3 


# **Indexing and slicing**

In [ ]:
arr = np.array([[10,20,30],[40,50,60]])
print(arr)


[[10 20 30]
 [40 50 60]]


In [ ]:
arr = np.array([10,20,30,40,50,60,70])

#1D indexing same as python list!!
print(f"Org array:\n{arr}")
print(f"first element: {arr[0]}")
print(f"last element: {arr[-1]}")
print(f"random element: {arr[3]}")
print(f"selcted elements: {arr[0:5]}")
print(f"selcted elements: {arr[6::-2]}")

#2D indexing
matrix = np.array([[1,2,3,],[4,5,6],[7,8,9]])
print(f"2D array:\n{matrix}")
print(f"Element at row 0 , column 0:-->{matrix[0,0]} ")#row,column
print(f"Element at row 1 , column 1:-->{matrix[1,1]} ")#row,column
print(f"Element at row 2 , column 2:-->{matrix[2,2]} ")#row,column
print(f"first row:{matrix[0,:]}")
print(f"first column:{matrix[:,0]}")
print(f"first 2 rows:\n{matrix[0:2,1:3]}")

# Boolean indexing - powerfull feature!!
arr = np.array([1,2,3,4,5,60,70])
print(f"org array: {arr}")
print(f"Elements greater than 5!: {arr[arr>5]}")
print(f"Even number: {arr[arr%2==0]}")


Org array:
[10 20 30 40 50 60 70]
first element: 10
last element: 70
random element: 40
selcted elements: [10 20 30 40 50]
selcted elements: [70 50 30 10]
2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 0 , column 0:-->1 
Element at row 1 , column 1:-->5 
Element at row 2 , column 2:-->9 
first row:[1 2 3]
first column:[1 4 7]
first 2 rows:
[[2 3]
 [5 6]]
org array: [ 1  2  3  4  5 60 70]
Elements greater than 5!: [60 70]
Even number: [ 2  4 60 70]


In [ ]:


arr_4d = np.array([
    # ── volume 0 ──────────────────────────────────────────────────────────────────
    [
        [[1,  2,  3,  4,  5],  [6,  7,  8,  9,  10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]],   # matrix 0
        [[21, 22, 23, 24, 25], [26, 27, 28, 29, 30], [31, 32, 33, 34, 35], [36, 37, 38, 39, 40]],   # matrix 1
        [[41, 42, 43, 44, 45], [46, 47, 48, 49, 50], [51, 52, 53, 54, 55], [56, 57, 58, 59, 60]],   # matrix 2
    ],
    # ── volume 1 ──────────────────────────────────────────────────────────────────
    [
        [[61, 62, 63, 64, 65], [66, 67, 68, 69, 70], [71, 72, 73, 74, 75], [76, 77, 78, 79, 80]],   # matrix 0
        [[81, 82, 83, 84, 85], [86, 87, 88, 89, 90], [91, 92, 93, 94, 95], [96, 97, 98, 99, 100]],  # matrix 1
        [[101,102,103,104,105],[106,107,108,109,110],[111,112,113,114,115],[116,117,118,119,120]],    # matrix 2
    ],
])

print(arr_4d.shape)  # (2, 3, 4, 5) ✅
print(arr_4d.ndim)   # 4 ✅
print(arr_4d.size)   # 120 ✅

(2, 3, 4, 5)
4
120


# **ARRAY OPERATIONS**

# Element-wise operations

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

print("a:",a)
print("b:",b)


print("SUM a,b: ", a+b)
print("MULTI a,b: ", a*b)
print("SUB a,b: ", a-b)
print("Division a,b: ", a/b)
print("power a,b: ", a**b)
print("Square root a: ", np.sqrt(a))

a: [1 2 3 4 5]
b: [ 6  7  8  9 10]
SUM a,b:  [ 7  9 11 13 15]
MULTI a,b:  [ 6 14 24 36 50]
SUB a,b:  [-5 -5 -5 -5 -5]
Division a,b:  [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
power a,b:  [      1     128    6561  262144 9765625]
Square root a:  [1.         1.41421356 1.73205081 2.         2.23606798]


# **Scaler operations**

In [ ]:
print("a + 10: ", a+10)
print("a * 10: ", a*2)
print("a + 10: ", a**3)


a + 10:  [11 12 13 14 15]
a * 10:  [ 2  4  6  8 10]
a + 10:  [  1   8  27  64 125]


# **Comparison operations**

In [ ]:
print("a > 2: ", a > 2)
print("a == 3: ", a == 3)
print("a <= 2: ", a <= 2)

a > 2:  [False False  True  True  True]
a == 3:  [False False  True False False]
a <= 2:  [ True  True False False False]


# **Array Manipulation**

In [ ]:
arr = np.arange(12)
print(f"Org array: {arr}")

reshaped = arr.reshape(2,2,3)
print(f"Reshaped array: \n{reshaped}")

reshaped1 = arr.reshape(4,3)
print(f"Reshaped array: \n{reshaped1}")

print(f"flatten: {reshaped1.flatten()}")

auto_reshaped = arr.reshape(2,2,-1)   #-1 means calculate automatically!!
print(f"auto reshaped: \n{auto_reshaped}")
print(auto_reshaped.ndim)

auto_reshaped = arr.reshape(-1,2)
print(f"auto reshaped: \n{auto_reshaped}")

#transpose:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"Org matrix: \n", matrix)
print(f" Matrix transpose(matrix.T): \n",matrix.T)

#concatination:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print("array a: ",a)
print("array b: ",b)

print(f"vertical concatination of a,b: \n{np.vstack((a, b))}")
a1 = np.vstack((a, b))
print(a1.shape)
print(f"horizontal concatination of a,b: \n{np.hstack((a, b))}")
a2 = np.hstack((a, b))
print(a2.shape)

print(np.concatenate((a, b), axis=0)) #axis = 0 for vertical
print(np.concatenate((a, b), axis=1)) #axis = 1 for horizontal



Org array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array: 
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
Reshaped array: 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
flatten: [ 0  1  2  3  4  5  6  7  8  9 10 11]
auto reshaped: 
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
3
auto reshaped: 
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
Org matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
 Matrix transpose(matrix.T): 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
array a:  [[1 2]
 [3 4]]
array b:  [[5 6]
 [7 8]]
vertical concatination of a,b: 
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)
horizontal concatination of a,b: 
[[1 2 5 6]
 [3 4 7 8]]
(2, 4)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


# **DIMENSIONS AND AXIS**



*   Dimensionns(ndim): number of axis(1D = 1, 2D=2, 3D=3)

1D = [1,2,3,4]

2D = [[1,2],[3,4]]

3D = [
      [[1,2,3],[4,5,6]],
      [[7,8,9],[10,11,12]],
      ]

*   Axis = The dimension along which as operation is performed (starts at 0)

*  Shape = Size of each dimension(e.g., (3,4) = 3 rows , 4 columns)(2D)

  (e.g., (2,3,4) = 2 martix , 3 row , 4 columns)(3D)

  (e.g., (2,2,3,4) = 2 page or tensor , 2 matrix 3 row , 4 columns)(4D)

for 2D array: axis=0 = rows (vertical), axis = 1 = columns (horizontal)

In [ ]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"Org matrix: \n", matrix)
print(f"shape: {matrix.shape}")
print(f"dimension: {matrix.ndim}")

#axis = 0: collapse rows ( sum columns wise)-> one value per columns and 1 row at the end.
sum_axis_0 = np.sum(matrix, axis=0)
print(f"sum of axis = 0: {sum_axis_0}")
print(f"shape of sum_axis_0: {sum_axis_0.shape} ")
print(f"ndim of sum_axis_0: {sum_axis_0.ndim} ")

# sum_axis_0_vstack = np.vstack(sum_axis_0)
# print(f"sum_axis_0_vstack: \n{sum_axis_0_vstack}")
# print("shape: ",sum_axis_0_vstack.shape)

sum_axis_1 = np.sum(matrix, axis=1)
print(f"sum of axis = 1: {sum_axis_1}")
print(f"shape of sum_axis_1: {sum_axis_1.shape} ")
print(f"ndim of sum_axis_1: {sum_axis_1.ndim} ")


Org matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
shape: (3, 3)
dimension: 2
sum of axis = 0: [12 15 18]
shape of sum_axis_0: (3,) 
ndim of sum_axis_0: 1 
sum of axis = 1: [ 6 15 24]
shape of sum_axis_1: (3,) 
ndim of sum_axis_1: 1 


In [ ]:
#3D array: more than 2 ndim
#Think:(pages(matrix), rows(vector) , columns) or (depth , height , width)

arr_3D = np.array(
    [
        [[1,2,3],[4,5,6]],
        [[7,8,9],[10,11,12]]
    ])
print(f"Org array: \n{arr_3D}")
print(f"shape: {arr_3D.shape} --> (matrix = 2, rows = 2, columns = 3)") #think like 2 pages each have 2x3 matrix(2D)
print(f"dimension: {arr_3D.ndim}")

sum_axis0_3D = np.sum(arr_3D, axis=0)
print(f"sum of axis = 0: \n{sum_axis0_3D}")
print(f"shape of sum_axis0_3D: {sum_axis0_3D.shape} ")
print(f"ndim of sum_axis0_3D: {sum_axis0_3D.ndim} ")

print("\n")

sum_axis1_3D = np.sum(arr_3D, axis=1)
print(f"sum of axis = 1: \n{sum_axis1_3D}")
print(f"shape of sum_axis0_3D: {sum_axis1_3D.shape} ")
print(f"ndim of sum_axis0_3D: {sum_axis1_3D.ndim} ")

print("\n")

sum_axis2_3D = np.sum(arr_3D, axis=2)
print(f"sum of axis = 2: \n{sum_axis2_3D}")
print(f"shape of sum_axis0_3D: {sum_axis2_3D.shape} ")
print(f"ndim of sum_axis0_3D: {sum_axis2_3D.ndim} ")
print("example: matrix[0,0] --> [1,2,3] = 1+2+3 = 6")


Org array: 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
shape: (2, 2, 3) --> (matrix = 2, rows = 2, columns = 3)
dimension: 3
sum of axis = 0: 
[[ 8 10 12]
 [14 16 18]]
shape of sum_axis0_3D: (2, 3) 
ndim of sum_axis0_3D: 2 


sum of axis = 1: 
[[ 5  7  9]
 [17 19 21]]
shape of sum_axis0_3D: (2, 3) 
ndim of sum_axis0_3D: 2 


sum of axis = 2: 
[[ 6 15]
 [24 33]]
shape of sum_axis0_3D: (2, 2) 
ndim of sum_axis0_3D: 2 
example: matrix[0,0] --> [1,2,3] = 1+2+3 = 6


# **STATISTICAL OPERATIONS**

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(f"Org array: {arr}")

#basic statistics:(1D)
print(f"sum: {np.sum(arr)}")
print(f"mean: {np.mean(arr)}")
print(f"median: {np.median(arr)}")
print(f"standard deviation: {np.std(arr)}")
print(f"variance: {np.var(arr)}")
print(f"Min: {np.min(arr)}")
print(f"Max: {np.max(arr)}")
print(f"Index of Min: {np.argmin(arr)}")
print(f"Index of Max: {np.argmax(arr)}")

print("\n")
#2D Array statistics:(with axis parameter)
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"Org matrix: \n", matrix)
print(f"sum: {np.sum(matrix,axis=0)}")
print(f"mean: {np.mean(matrix,axis=0)}")
print(f"median: {np.median(matrix,axis=0)}")
print(f"standard deviation: {np.std(matrix,axis=0)}")
print(f"variance: {np.var(matrix,axis=0)}")
print(f"Min: {np.min(matrix,axis=1)}")
print(f"Max: {np.max(matrix,axis=1)}")
print(f"Index of Min: {np.argmin(matrix,axis=1)}")
print(f"Index of Max: {np.argmax(matrix,axis=1)}")

Org array: [1 2 3 4 5 6 7 8 9]
sum: 45
mean: 5.0
median: 5.0
standard deviation: 2.581988897471611
variance: 6.666666666666667
Min: 1
Max: 9
Index of Min: 0
Index of Max: 8


Org matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
sum: [12 15 18]
mean: [4. 5. 6.]
median: [4. 5. 6.]
standard deviation: [2.44948974 2.44948974 2.44948974]
variance: [6. 6. 6.]
Min: [1 4 7]
Max: [3 6 9]
Index of Min: [0 0 0]
Index of Max: [2 2 2]


# **LINEAR ALGEBRA**

# **USEFULL ARRAY MEATHODS**

In [ ]:
arr = np.array([1,12,14,13,3,5,6,27,23,18,69])
print(f"Org array: {arr}")

print("\n")#sorting
sorted_arr = np.sort(arr) #create a copy and sort that!
print(f"sorted array: {sorted_arr}")
print(arr)

arr.sort() #sort org!!
print(f"sorted array: {arr}")

print("\n")#Searching!!
arr = np.array([1,12,14,13,3,5,6,27,23,18,69])
print(f"Org array: {arr}")

print(f"where is value > 5?: {np.where(arr>5)}") #showing indexs
print(f"value where condition is true: {arr[np.where(arr>5)]}")

print("\n")#Unique elements!!
arr_dupluicates = np.array([1,1,1,2,3,3,2,2,3,4,5,6,7])
print(f"Org array: {arr_dupluicates}")
print(f"Unique elements: {np.unique(arr_dupluicates)}")


Org array: [ 1 12 14 13  3  5  6 27 23 18 69]


sorted array: [ 1  3  5  6 12 13 14 18 23 27 69]
[ 1 12 14 13  3  5  6 27 23 18 69]
sorted array: [ 1  3  5  6 12 13 14 18 23 27 69]


Org array: [ 1 12 14 13  3  5  6 27 23 18 69]
where is value > 5?: (array([ 1,  2,  3,  6,  7,  8,  9, 10]),)
value where condition is true: [12 14 13  6 27 23 18 69]


Org array: [1 1 1 2 3 3 2 2 3 4 5 6 7]
Unique elements: [1 2 3 4 5 6 7]


# **EXAMPLE: DATA ANALYSIS**

In [ ]:
#simulate a grayscale image(2D array) with values 0-255
#lets create a simple 10x10 "image"
image = np.random.randint(0,256,size=(10,10))
print("Org image (10x10 array)")
print(image)


#Brightness adjustment(add constant)
brighter = np.clip(image + 50, 0, 255) # clip to valid range
print(f"\n Brightness increased( mean: {np.mean(brighter):.2f})")


#contrast adjustment(Multiply)
brighter = np.clip(image * 1.55, 0, 255) # clip to valid range
print(f"\n Brightness increased( mean: {np.mean(brighter):.2f})")

Org image (10x10 array)
[[115 249 176  61 211 177 108  98  36 192]
 [ 43 137 209 157   4 199  12  37 231 126]
 [227 155 211  43 253  18   9 195  39  80]
 [ 83 163  63 244 109 201   8   1 145   9]
 [ 74  23 163 191  89  12  28 149  17 155]
 [ 19 178  40 180 148  20  86 236  98 134]
 [109   8 251  56  91 109  31   0 109  15]
 [ 16 166 224  62  54 156  10  43  44 248]
 [ 36  11 248  25  41  80 222 239 171  11]
 [  4 229 100  20  30  29 148  23 111 215]]

 Brightness increased( mean: 152.07)

 Brightness increased( mean: 144.19)


In [ ]:
#simulate student test score (3 test, 5 students)
scores = np.array([
    [85, 95, 88],  #stu 1
    [92, 87, 91],  #stu 2
    [78, 82, 80],  #stu 3
    [95, 98, 96],  #stu 4
    [88, 85, 90],  #stu 5
])

print("test score Maatrix(5 students, 3 tests): ")
print(scores)


#calculate statistics
student_avg = np.mean(scores, axis = 1)
test_avg = np.mean(scores, axis = 0)
print(f"avg score per student{student_avg}")
print(f"avg score per test{test_avg}")

print("\n")
print(f"best test avg: {np.max(test_avg)}")
print(f"worst test avg: {np.min(test_avg)}")

print("\n")
print(f"best student avg: {np.max(student_avg)}")
print(f"student with best average (index): {np.argmax(student_avg)}")
print(f"worst student avg: {np.min(student_avg)}")

print("\n---Test statistics---")
test_avg = np.mean(scores, axis = 0)
print(f"avg score per test{test_avg}")
print(f"worst test (lowst)avg:{np.argmin(test_avg)} ")
print(f"best test (higest)avg:{np.argmax(test_avg)} ")

test score Maatrix(5 students, 3 tests): 
[[85 95 88]
 [92 87 91]
 [78 82 80]
 [95 98 96]
 [88 85 90]]
avg score per student[89.33333333 90.         80.         96.33333333 87.66666667]
avg score per test[87.6 89.4 89. ]


best test avg: 89.4
worst test avg: 87.6


best student avg: 96.33333333333333
student with best average (index): 3
worst student avg: 80.0

---Test statistics---
avg score per test[87.6 89.4 89. ]
worst test (lowst)avg:0 
best test (higest)avg:1 
